// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master_sm.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_master_5fsm_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_master_5fsm_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_master_5fsm_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_master_5fsm_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_master_5fsm_2eproto;
namespace phxpaxos {
class MasterOperator;
class MasterOperatorDefaultTypeInternal;
extern MasterOperatorDefaultTypeInternal _MasterOperator_default_instance_;
}  // namespace phxpaxos
PROTOBUF_NAMESPACE_OPEN
template<> ::phxpaxos::MasterOperator* Arena::CreateMaybeMessage<::phxpaxos::MasterOperator>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace phxpaxos {

// ===================================================================

class MasterOperator :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:phxpaxos.MasterOperator) */ {
 public:
  MasterOperator();
  virtual ~MasterOperator();

  MasterOperator(const MasterOperator& from);
  MasterOperator(MasterOperator&& from) noexcept
    : MasterOperator() {
    *this = ::std::move(from);
  }

  inline MasterOperator& operator=(const MasterOperator& from) {
    CopyFrom(from);
    return *this;
  }
  inline MasterOperator& operator=(MasterOperator&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MasterOperator& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MasterOperator* internal_default_instance() {
    return reinterpret_cast<const MasterOperator*>(
               &_MasterOperator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MasterOperator& a, MasterOperator& b) {
    a.Swap(&b);
  }
  inline void Swap(MasterOperator* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MasterOperator* New() const final {
    return CreateMaybeMessage<MasterOperator>(nullptr);
  }

  MasterOperator* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MasterOperator>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MasterOperator& from);
  void MergeFrom(const MasterOperator& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MasterOperator* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "phxpaxos.MasterOperator";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_master_5fsm_2eproto);
    return ::descriptor_table_master_5fsm_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNodeidFieldNumber = 1,
    kVersionFieldNumber = 2,
    kTimeoutFieldNumber = 3,
    kOperatorFieldNumber = 4,
    kLastversionFieldNumber = 6,
    kSidFieldNumber = 5,
  };
  // required uint64 nodeid = 1;
  bool has_nodeid() const;
  void clear_nodeid();
  ::PROTOBUF_NAMESPACE_ID::uint64 nodeid() const;
  void set_nodeid(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // required uint64 version = 2;
  bool has_version() const;
  void clear_version();
  ::PROTOBUF_NAMESPACE_ID::uint64 version() const;
  void set_version(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // required int32 timeout = 3;
  bool has_timeout() const;
  void clear_timeout();
  ::PROTOBUF_NAMESPACE_ID::int32 timeout() const;
  void set_timeout(::PROTOBUF_NAMESPACE_ID::int32 value);

  // required uint32 operator = 4;
  bool has_operator_() const;
  void clear_operator_();
  ::PROTOBUF_NAMESPACE_ID::uint32 operator_() const;
  void set_operator_(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // optional uint64 lastversion = 6;
  bool has_lastversion() const;
  void clear_lastversion();
  ::PROTOBUF_NAMESPACE_ID::uint64 lastversion() const;
  void set_lastversion(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // required uint32 sid = 5;
  bool has_sid() const;
  void clear_sid();
  ::PROTOBUF_NAMESPACE_ID::uint32 sid() const;
  void set_sid(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:phxpaxos.MasterOperator)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint64 nodeid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 version_;
  ::PROTOBUF_NAMESPACE_ID::int32 timeout_;
  ::PROTOBUF_NAMESPACE_ID::uint32 operator__;
  ::PROTOBUF_NAMESPACE_ID::uint64 lastversion_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sid_;
  friend struct ::TableStruct_master_5fsm_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MasterOperator

// required uint64 nodeid = 1;
inline bool MasterOperator::has_nodeid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MasterOperator::clear_nodeid() {
  nodeid_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MasterOperator::nodeid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.nodeid)
  return nodeid_;
}
inline void MasterOperator::set_nodeid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000001u;
  nodeid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.nodeid)
}

// required uint64 version = 2;
inline bool MasterOperator::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MasterOperator::clear_version() {
  version_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MasterOperator::version() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.version)
  return version_;
}
inline void MasterOperator::set_version(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  version_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.version)
}

// required int32 timeout = 3;
inline bool MasterOperator::has_timeout() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MasterOperator::clear_timeout() {
  timeout_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MasterOperator::timeout() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.timeout)
  return timeout_;
}
inline void MasterOperator::set_timeout(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  timeout_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.timeout)
}

// required uint32 operator = 4;
inline bool MasterOperator::has_operator_() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MasterOperator::clear_operator_() {
  operator__ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MasterOperator::operator_() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.operator)
  return operator__;
}
inline void MasterOperator::set_operator_(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  operator__ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.operator)
}

// required uint32 sid = 5;
inline bool MasterOperator::has_sid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MasterOperator::clear_sid() {
  sid_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MasterOperator::sid() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.sid)
  return sid_;
}
inline void MasterOperator::set_sid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  sid_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.sid)
}

// optional uint64 lastversion = 6;
inline bool MasterOperator::has_lastversion() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MasterOperator::clear_lastversion() {
  lastversion_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 MasterOperator::lastversion() const {
  // @@protoc_insertion_point(field_get:phxpaxos.MasterOperator.lastversion)
  return lastversion_;
}
inline void MasterOperator::set_lastversion(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  lastversion_ = value;
  // @@protoc_insertion_point(field_set:phxpaxos.MasterOperator.lastversion)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace phxpaxos

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_master_5fsm_2eproto
