#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for replicadstorage
#
# IDENTIFICATION
#    src/backend/replicadstorage/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/replicadstorage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = libpaxos

OBJS = rstorage.o

include $(top_srcdir)/src/backend/common.mk
